// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jglwfatcrmyvslluobie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbHdmYXRjcm15dnNsbHVvYmllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDA2OTcsImV4cCI6MjA2ODA3NjY5N30.txByRgVVo_vIjbyKOWCuR5f6laPc9L5pQlwfCaSwmHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});